spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/goodtown
    username: town
    password: goodtown
  data:
    redis:
      host: localhost
      port: 6379
#      password: 123456
      timeout: 2000s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  configuration: # setting配置
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.goodtown.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /

jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: goodtown123456  #当前程序签名秘钥 自定义

tengxun:
  cos:
    SecretId: AKIDWyLqVCnFcu7BNWYp0P6qjqvpwNrSl8fQ
    SecretKey: WvGYyJeyVyRsT3py8Gf0QhwNclx7IMUf
    region: ap-beijing
    bucketName: sky-take-out-1317682162
    url: https://sky-take-out-1317682162.cos.ap-beijing.myqcloud.com/
    path: goodtown/